### ISSUE TITLE
Exception instead of error message

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#130]
INFO: Enqueuing jenkins slave request
Jun 18, 2015 5:17:54 PM hudson.slaves.NodeProvisioner$2 run
INFO: MesosCloud provisioning successfully completed. We have now 22 computer(s)
java.lang.NullPointerException
        at org.jenkinsci.plugins.mesos.JenkinsScheduler.matches(JenkinsScheduler.java:306)
        at org.jenkinsci.plugins.mesos.JenkinsScheduler.resourceOffers(JenkinsScheduler.java:252)
Jun 18, 2015 5:17:55 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
SEVERE: The Mesos driver was aborted! Status code: 3

My current config gets to the point of attempting a connection to the node and never succeeds. It is not clear how this works. Is JNLP required. Is there setup on the nodes required.

**Comment by geoffroyjabouley** [comment]
Hello
could be the same as https://github.com/jenkinsci/mesos-plugin/issues/113 ?

**Comment by digitalrinaldo** [comment]
I don't think so.  I have downloaded the latest master and installed that plugin.  Other issues appear to be resolved but this one doesn't.  It is also adding frameworks to mesos that don't seem to be removed when the exception occurs.  What I am seeing is the error message and a jenkins console log that says either 

   404 which is another bug
         why is the node still in the table if it has gone away and 

   Starting mesos slave mesos-jenkins-e7e24a84-a718-4724-a077-8b6092bc9517
       This never returns and all previous diagnostics don't work.

The use of the Google logging package also complicates things since it has a very simple minded view of logging only three levels and even worse it splits the logs into three files. It makes one wonder if any of these programmers have ever worked on production systems.  They are doing so many things that are different but not helpful.

**Comment by geoffroyjabouley** [comment]
Don't hesitate to contact Mesos developpers and teach them how to develop a production ready system.

Btw, your issue looks exactly like this: https://github.com/jenkinsci/mesos-plugin/issues/111
I have faced similar problem when my mesos cluster resources where exhausted. In your case, reading your first message, you have already 22 slaves, so maybe mesos resources were all allocated.
You could configure your Jenkins Mesos slaves idle timeout more agressively to unused slaves are deleted more often.

If you think your issue is different, please add:
Your mesos cluster version + jenkins version
any helpfulls logs from the Jenkins master, the jenkins slaves, the mesos master, the mesos slaves, etc...

**Comment by digitalrinaldo** [comment]
Thanks I patched some of these issues locally and will update once 0.8 comes out.
