### ISSUE TITLE
Plugin doesn't pull latest image when run jenkins slave in docker.

### ISSUE THREAD

**Issue by XiaokunHou** [jenkinsci/mesos-plugin#132]
I specified docker image and try to launch jenkins in docker container. But it will always use local images rather than pull updates from registry. 

Any other workarounds? From example, run commands from container to host machines to update images so that next time updated image will be used.

**Comment by XiaokunHou** [comment]
Or I must use docker in docker..

**Comment by geoffroyjabouley** [comment]
have you checked if docker at least tries to pull the image from the
registry?
I think you can get this info from the docker logs
(/var/log/upstart/docker.log on ubuntu)

2015-06-19 11:08 GMT+02:00 XiaokunHou <notifications@github.com>:

**Comment by XiaokunHou** [comment]
where is the log for rhel7.1? Cannot find log in /var/lib/docker

**Comment by bhuvan** [comment]
if you use __latest__ tag, that's specific to docker, not the plugin. each docker image should be tagged with unique version. if same version is already pulled, it won't be pulled again even if it's changed in the registry.

**Comment by nickithewatt** [comment]
@XiaokunHou  we have encountered the same thing for our development - this is currently due to the way in which mesos is integrated with docker, however a change was made in Mesos 0.22 to make this a configurable option which would allow for the behaviour you currently seek. See https://issues.apache.org/jira/browse/MESOS-1886.

This is not however available in the mesos-plugin thought - Once we upgrade to 0.22 we plan to contribute a PR to make this configurable in the mesos-plugin as well if not done already.

**Comment by geoffroyjabouley** [comment]
There is indeed a forcePull option available when creating a docker mesos task using Marathon.

Having such an option for the jenkins-mesos plugin will be great (and is needed)!

Btw, the plugin already works fine with mesos 0.22.1, so a mesos version bump in the pom.xml file might be possible without any problem...

**Comment by jeschkies** [comment]
As force pull is an option I assume this has been fixed. Feel free to reopen the issue if it is not fixed for you.
