### ISSUE TITLE
Will Mesos plugin support slaves connected through SSH, not JNLP?

### ISSUE THREAD

**Issue by recyard** [jenkinsci/mesos-plugin#144]
In some reason I'm more comfortable connecting my Jenkins slaves through SSH, then I can do more customization like adding environment variables inside the docker images. By far I know this plugin can only use JNLP connection, so is there a plan to add SSH?

**Comment by vinodkone** [comment]
No plans yet for SSH. Do you know what it takes to get that support included (key distribution, shared password etc)? If it's fairly straightforward we would be happy to add the support.

**Comment by digitalrinaldo** [comment]
Yes I am pretty expert at that -- JNLP is really bad for scaling. If we have 100 nodes we get 100 processes running it will never scale as mesos scales.

**Comment by anomalizer** [comment]
Key distribution should not be much of a hassle as the public keys can be baked inside the docker images used for slaves. The exhaustive set of expectations from the slaves would be as follows:
* sshd is running on a fixed port so that jenkins knows which port to ssh into
* There is a preconfigured user with the appropriate public keys on the slave (docker images)

**Comment by jeschkies** [comment]
@digitalrinaldo, do you have some numbers comparing JNLP vs SSH?
