### ISSUE TITLE
Termination of many nodes

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#164]
After the jenkins mesos plugin has been given a resource to use and the use of the resource is complete the Jenkins UI is unreadable, nodes are left in the following state for 1 minute.  Can this time be reduced or can the node be removed from the ui in some way.
<img width="323" alt="screen shot 2015-09-22 at 5 14 59 pm" src="https://cloud.githubusercontent.com/assets/799458/10032035/8c1b3668-614e-11e5-9063-6c87b9c88898.png">

**Comment by vinodkone** [comment]
These Jenkins slaves should go offline (and removed from the Jenkins UI)
when they are idle for a configured amount of 'idle termination' time
(default might be 1 min). I'm a bit surprised that offline slaves stay for
1 minute in the UI. It's probably because of a recent code change that
introduced an asynchronous cleanup thread.


-- Vinod

**Comment by jeschkies** [comment]
Closed by #173.
