### ISSUE TITLE
Jenkins can only launch slaves when talking to current mesos master 

### ISSUE THREAD

**Issue by mwmanley** [jenkinsci/mesos-plugin#306]
I have redundant mesos masters that elect through ZooKeeper, as is custom.  Other applications like marathon seem to be able to handle finding the master on their own, but Jenkins seems to only need to be connected to a single master, but has to be connected to the elected master.  So if this master moves due to maintenance or whatever, then Jenkins loses connectivity and cannot launch any slaves.

Has anyone else seen this behaviour?  We're running 1.2 here.  If there is something grossly missing or if I have the ability to enumerate all my masters and it can do the right thing from there, please let me know.  Otherwise, this seems like a bug.

Thanks much!

**Comment by aleksejlopasov** [comment]
+1
Just wanted to create a new issue but found this one first.
The same behavior - Jenkins connects to current active master only. If master role jumps to another server, then Jenkins loses connectivity and no slaves created any more until Jenkins restarts

To solve this I have the temporary solution - another service that resolves name 'leader.mesos' and every 20 seconds, if ip address has changed, then restart signal to Jenkins is sent
(Of course mesos-dns service has be deployed to resolve 'leader.mesos' name)

Please implement feature of finding new master automatically (like marathon/chronos frameworks)

P.S. I tried to create three mesos clouds in Jenkins each configured to its own mesos-master (Only one had a chance to register in mesos due to only one mesos-master is active at the moment). The result is the same

**Comment by sumeshkanayi** [comment]
We have the same problem too

**Comment by mwmanley** [comment]
Once I set it up to use the mesos zookeeper nodes, then it followed the master correctly.  It uses the same syntax as mesos itself with the zk://whatever:2181/path. 

I forgot to close this!

**Comment by mwmanley** [comment]
That's putting the zk paths where it currently asks for the mesos master, I believe.  We moved to k8s from mesos, so I no longer have the syntax handy.
