### ISSUE TITLE
Launch dynamic slave image from Mesos-plugin

### ISSUE THREAD

**Issue by tangicolin** [jenkinsci/mesos-plugin#66]
Today jenkins slave configuration are static. Container Image to launch is statically define into Jenkins configuration. 

It would be a nice feature to be able to put some "Jenkins Variable" compute from a master Jobs into the container image fields to be able to dynamically choose Container Image reference of a Mesos Jenkins slave. 

Today I need to launch a basic slave that launch the container that i want (Docker-in-Docker).

**Comment by barkerd427** [comment]
You can add more than one image currently. Are you wanting to launch a container as the build that may have tests or something else in it? I think adding configuration for a slave in the job config page would be a good solution to allowing users to provision what they need.

**Comment by tangicolin** [comment]
Today i can add more than one image but they should already be defined into Jenkins mesos configuration. 
Yes adding configuration for a slave in the job config page would be a great feature. With this i can chose which docker image i launch from jenkins job variable.
 What i want to achieve is to have one to one binding between  sha1 git code and docker tag.
With this, for every new commit, i can get commit parent and launch corresponding docker image (git clone will be faster (fetch only one commit) and i'm sure to have right environment (tools into my docker with right version ...)). With this system i can solve the problem of versionning binary (git for code and docker for everything else).

**Comment by kmadel** [comment]
The Jenkins Workflow Plugin has great Docker support for this where you specify the docker image to use for the build environment in the workflow (you may also want to include the Docker binary/client only):

```docker.image('ruby').inside { [ruby build, etc]}```

And rather than use docker-in-docker you could use docker-outside-docker by mapping the mesos Docker host socket into a plain vanilla Jenkins slave image:

```-v /var/run/docker.sock:/var/run/docker.sock```

This has the added advantage over DIND that 'build' images will be shared from the mesos host (not re-downloaded to each mesos slave).  And regarding 'build' images, it will allow you to have non-Java build images, like for Ruby.

*You could also use the Docker Custom Build Environment plugin.

**Comment by sebinsua** [comment]
Is this still not a supported feature? 

Seems fairly standard nowadays to build your docker images on an early CI stage, and then run parallel docker containers on different nodes for further stages.

**Comment by jeschkies** [comment]
I did not prune the feature requests yet. Would `docker.image('ruby').inside { [ruby build, etc]}` work for you? I had a similar request a while ago. IMHO users should bring their Docker image.

**Comment by sebinsua** [comment]
Please can we keep this open unless such a feature has been added?

**Comment by jeschkies** [comment]
@sebinsua, sure. Could you reply to my comment from November?
