### ISSUE TITLE
Need jnlpSecret environment variable to pass to launched mesos workers

### ISSUE THREAD

**Issue by bacoboy** [jenkinsci/mesos-plugin#72]
In a jenkins environment with authentication enabled (in this case ldap), the dynamically generated slaves in mesos cannot connect back to the master because JNLP credentials of some kind are needed.

One option that has been suggested is to create an account (in this case ldap) so the slaves can authenticate.  However, this creates an external dependency that this account be setup, the password never expire, etc. which are not easy requirements in most big enterprise environments.

If you setup a JNLP slave (non-mesos), you can use the jnlpSecret option instead which is based on the slave name and some internal key known only to the jenkins master.  Even if the key could be extracted, in a mesos slave world, the worker names are essentially random (for instance, ``mesos-jenkins-47c9dfa3-ed54-4fd5-b850-90a568b2b6ff``) -- hardly something I can put in the configuration box for ``Additional Jenkins Slave Agent JNLP arguments``.

Of course all this is known by the master and/or mesos-plugin.  The root secret, the mesos worker name being launched -- everything needed to calculate this value.  There are even [chef recipes](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/slave_jnlp.rb#L104) to do this for slaves configured via chef.  Why can't we populate an environment variable (say ``$JNLP_SECRET``) that I can pass in the agent argument box (``-jnlpSecret $JNLP_SECRET``) or just have a checkbox for "Authorize automatically via JNLP secret"?

**Comment by geoffroyjabouley** [comment]
Hello
this would be great to have the possibility to automatically use the -secret option, so that you don't need credentials to be stored on the configuration file.

Have a look here: https://issues.jenkins-ci.org/browse/JENKINS-18342?focusedCommentId=188162&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-188162

It explains how to get the -secret value option (jnlp mac) from Jenkins master.

So as soon as the computer is created by Jenkins, the command line to start the slave.jar file should be updated with the secret value BEFORE the request is send to the Mesos cluster to instanciate the slave

**Comment by maselvaraj** [comment]
@bacoboy @geoffroyjabouley . I've added the '-secret' option in this pull request: https://github.com/jenkinsci/mesos-plugin/pull/84. Jenkins would automatically configure '-secret' whenever it spawns a mesos slave.

**Comment by bacoboy** [comment]
**Thank You!**

Looking forward to the next release :)

**Comment by maselvaraj** [comment]
@bacoboy Please check the latest release of the plugin (0.6.0). It includes '-secret' option.
I'm closing this issue.
