### ISSUE TITLE
Slave username appears to be ignored

### ISSUE THREAD

**Issue by william-richard** [jenkinsci/mesos-plugin#95]
Hello,

I'm trying to set up this plugin.

I've been able to get it to create a mesos framework, but when I schedule jobs, the tasks appear to fail with the following error message (from the slave logs):

```
failed to start: Failed to create container: Failed to chown: Failed to get user information for 'jenkins': Success
```

Nothing is written to the `stdout` or `stderr` files, I got that log using `journalctl` on the slave.

This is despite the fact that I have set the Slave Username to a different user (root) in the cloud configuration.
What is this configuration supposed to do?  Can I customize what user mesos uses to create the container?

I am using mesos plugin version 0.6.0, jenkins 1.605 and mesos 0.21.0.

Here's a screenshot of our mesos plugin configs:

![](https://www.dropbox.com/s/lgdywhlk9r5rrnr/Screenshot%202015-03-25%2011.51.08.png?dl=1)

Thank you!

**Comment by bacoboy** [comment]
I had this problem until I created a `jenkins` user in the `docker` group on the mesos-slave:

    sudo useradd -g docker jenkins

My docker/mesos-slave was centos7 which requires the user to be in the `docker` group to run docker commands.  This is because the file used by the docker command line to communicate with the docker daemon has this ownership:
```
$ docker ps
FATA[0000] Get http:///var/run/docker.sock/v1.17/containers/json: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?
$ ls -l /var/run/docker.sock
srw-rw---- 1 root docker 0 Mar 25 14:18 /var/run/docker.sock
```
By making `jenkins` part of the `docker` group, it is now able to launch the slave.

Not sure why setting that field to root -- I haven't changed it from the default myself...

Hope this helps in the meantime...

**Comment by bacoboy** [comment]
It may also be the `Remote FS Root` set to jenkins which gives you that error if your docker container doesn't have a `jenkins` user inside.

Seems like you need to check the `Use Docker Containerization` and specify an image to use for the dynamic slave...  It needs to have a `jenkins` user and `java` to run the slave jar downloaded from the jenkins master.  You can try `evarga/jenkins-slave:latest` or build your own...

**Comment by Primer42** [comment]
What I would really like is the ability to run the mesos slave run, and that's what I thought `Slave Username` did.  What does `Slave Username` actually do?  Is there some way I can run the mesos slave as a different user?

**Comment by bacoboy** [comment]
The mesos slave (meaning the mesos-slave process) _usually_ runs as `root` (at least it does on my centos7 system using mesosphere packages).  If you mean the jenkins slave run, then it seems to be what `RemoteFSRoot` is for -- but not 100% sure.  One thing seems clear (based on your screenshot) is that you have to pick one of the 2 checkboxes to decide what you are going to run -- a docker container or 'external' -- whatever that is...

If you pick a docker container as your jenkins slave it too has to have a jenkins user (and java) so the jenkins slave can be run.  Since the slave only runs in that docker container, it really doesn't matter what user it runs as (unless you are using a volume mount where permissions matter) so I just use the default `jenkins`

**Comment by Primer42** [comment]
Sorry for the confusion
I was seeing this same error regardless of the containerizer solution I chose (docker or external).  I also tried changing `RemoteFSRoot` and it did not have the intended effect of changing the user that ran inside the container.

**Comment by vinodkone** [comment]
Slave username tells the plugin what user to run the *Jenkins* slaves as (the current name is a bit confusing. I'll fix it on the master branch). Whatever user you pick, ensure that the user exists on the Mesos slave host or Docker container (if using Docker containerizer). The RemoteFSRoot doesn't have anything to do with the user running Jenkins slave.

**Comment by barkerd427** [comment]
I've run into this issue. It seems that when the user of the framework isn't available on a mesos-slave, the task fails with the above error. I understand that there may be a security concern of running a framework as a less privileged user who can then run commands as root, so this may be an issue that isn't easily resolved beyond creating a new user on each node. That doesn't seem like a good solution either. Converting each Jenkins master to use the same user might be a good option. I would like to be able to specify in Jenkins which user the framework should register as. I haven't looked at the code to determine the ease of this change.

@vinodkone, I think the 'Slave username' should be moved to the Docker config or container config. The user may be different in each Jenkins slave container.

**Comment by vinodkone** [comment]
Sorry for the delay in response.

The "Slave username" should be really named "Framework user". It is the
default user a mesos task (here Jenkins slave) is launched as. Each of the
SlaveInfo could also have its own user that will override the default. I
will try to commit a patch for this.

William, as others have mentioned, make sure your container has the
appropriate user installed.



-- Vinod

**Comment by chaitumemphis** [comment]
I have same use case to run jenkins slave as non root user. I am using above docker image (evarga/jenkins-slave:latest) and have set the Slave username as 'jenkins' and Remote FS Root as jenkins. Not sure what I am missing. Slave is failing to launch. It just says Starting mesos slave .... for long hours.Also in DCOS UI I see slave status as Lost. Any help is much appreciated.

**Comment by jeschkies** [comment]
Would you have the Mesos logs for the job? Did you try the new 2.0 plugin?

**Comment by jeschkies** [comment]
Closing for lack of response.
